### ISSUE TITLE
Bug Fixes 10/25/24

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#160] opened 2024-10-25 23:06 UTC
- [x] When hiding event locations from the API the 1337 Shows up in the panel as well as hiding the coordinate for an event
- [x] When you go to the Blacklist the page crashes(Check Coding)
- [x] Bans dont end when timer is up
- [x] Mod admin unable to delete post
- [x] Check bloodline rolling + information on pool
- [x] For Spars treat them as enemies right now they are treated as allies and certain tags don't work on them due to friendly fire. 
- [x] Can't have two of the same summoning on combat at the same time and sometimes summons give up when they are two on the field
- [x] I also noticed while I was testing the BL thing that that when I was switch between accounts and move on the map, I could make my characters kinda teleport to each other since one account would get updated with the position of the other one
- [x] A bug that needs to be fixed also is the one that makes the objective "collect_item" drop multiple of that item. In the current event we are running one person got 17 of the same item .
- [x] Leave sensei option
- [x] Highlight new messages on inbox 
- [x] Event Expiration Timer does not work
- [x] Pierce should be affected by Reflect,Absorb and Recoil(Right now it ignore those tags)
- [x] Movement Prevent should be cleansable. 
- [x] AI To Ignore Stat caps
- [x] Clear should affect Stealth
- [x] Clan leaders can't promote co-leader 
- [x] AIs are not destroying barriers or walking around them
- [x] Add Target empty ground, Ally on AIs
- [x] Add a Combo system for AIs so we can set what Jutsu they use in what order 
- [x] Can't Remove a rule on custom AIs
- [x] Daily Quest only show up sometimes not consistent for every player. 
- [x] Add double confirmation when a player is trying to drop an item marked as Event
- [x] Item Fix Doesn't apply to Syndicate 
- [x] Can we have it so that if you're max inventory, you just cannot buy more items?
- [x] Reward user Kogeratsu for finding the infinite BL bug
- [x] Push AI Rules to player profiles so they can customize their AIs
- [x] It seems that during spar, and sometimes in regular combat, the game doesn't see people from the same village as enemies and so a jutsu do what its supposed to
- [x] Badges for top supporters
- [x] Players Earns 5 Tokens per PVP Kill Anbu Earns 10 Tokens
- [x] Badge for having killed terr
- [x] Mod notifications are bugged
- [x] Fed with paypal gone?
- [x] Only destroy barriers if user is unreachable
- [x] #165
- [x] New condition for rule number 
- [x] Move on AOE to original target hex
- [x] Remove consumables from all Kage battle for both attacker and defender. It seems there's a bug that's allowing Kage to still take consumables into combat. I believe it might be caused by the overflow bug where if your inventory is full, it auto equips items.
- [x] Also Kage AI doesn't seem to respect item cooldowns so can we have both of those fixed ASAP? I know there's a larger Kage update to come, but for now we need these fixed as soon as you can since its actively causing an issue for players.

**Comment by d3t0ur** [comment] 2024-10-28 08:55
URGENT Update Needed. Remove consumables from all Kage battle for both attacker and defender. It seems there's a bug that's allowing Kage to still take consumables into combat. I believe it might be caused by the overflow bug where if your inventory is full, it auto equips items. 

Also Kage AI doesn't seem to respect item cooldowns so can we have both of those fixed ASAP? I know there's a larger Kage update to come, but for now we need these fixed as soon as you can since its actively causing an issue for players. @MathiasGruber

**Comment by MathiasGruber** [comment] 2024-11-07 15:21
Added to list of tasks

**Comment by MathiasGruber** [comment] 2024-11-07 17:21
Should all be fixed now

**Closed by MathiasGruber** 2024-11-07 17:21 UTC
